modLoader="javafml"
loaderVersion="[36,)"
license="https://github.com/ToCraft/Darkest-LotR/blob/master/LICENSE.md"
issueTrackerURL="https://github.com/ToCraft/Darkest-LotR/issues"
[[mods]]
modId="darkestlotr"
version="${version}"
displayName="Darkest LotR"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://github.com/ToCraft/Darkest-LotR/releases"
# logoFile="examplemod.png"
credits="Thanks for Mevan for creating the LotR-mod."
authors="Java and tech-stuff: To_Craft, Idea & Textures: DarkShadow_2k"
description='''

This Mod improves your expierence with our modpack and the LotR-mod.
It adds armor & weapons, improves spawning and adds new, magical entities from other mods to the world of Lotr.

'''
[[dependencies.darkestlotr]] #optional
    # the modid of the dependency
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.darkestlotr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.darkestlotr]]
    modId="lotr"
    mandatory=true
    versionRange="Renewed-5.5"
    ordering="NONE"
    side="BOTH"
